### ISSUE TITLE
[URGENT] update  6.2.1~ynh1  to 6.3.1~ynh1 is failing, deleting the app, and can't restore from backup

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mattermost_ynh#334]
### Describe the bug
update  6.2.1~ynh1  to 6.3.1~ynh1 is failing, deleting the app, and can't restore from backup

### Context

- Hardware: *VPS*
- YunoHost version: 
```
# yunohost -v
yunohost: 
  repo: stable
  version: 4.3.6.2
yunohost-admin: 
  repo: testing
  version: 4.3.4.1
moulinette: 
  repo: stable
  version: 4.3.3.1
ssowat: 
  repo: stable
```
- I have access to my server: *Through SSH & through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch:
```
  YNH_APP_MANIFEST_VERSION: 6.3.1~ynh1
  YNH_APP_UPGRADE_TYPE: UPGRADE_APP
  YNH_ARCH: amd64
  ```
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*
```
  YNH_APP_CURRENT_VERSION: 6.2.1~ynh1
  YNH_APP_ID: mattermost
  YNH_APP_INSTANCE_NAME: mattermost
  YNH_APP_INSTANCE_NUMBER: '1'
  YNH_APP_MANIFEST_VERSION: 6.3.1~ynh1
  YNH_APP_UPGRADE_TYPE: UPGRADE_APP
```
upgrade is deleteting the app: 
```
# yunohost app info mattermost
Error: Could not find mattermost in the list of installed apps
```
### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    yunohost app upgrade mattermost
    ```
- **restoration from webui is failling** and in cli aswell**

### Logs
upgrade failing logs: https://paste.yunohost.org/raw/adimojowib
restoration failing logs: https://paste.yunohost.org/raw/fucifejali
